remote_theme: pmarsceill/just-the-docs

title: Atomic Calendar Revive
description: A Home Assistant Plugin to add a nice calendar view

# Specific to this theme
search_enabled: true
search_tokenizer_separator: /[\s/]+/
ga_tracking: UA-XXXXX-Y
heading_anchors: true
color_scheme: "dark"
footer_content: "Copyright &copy; 2017-2020 Steven Marks. Distributed by an <a href=\"https://github.com/marksie1988/atomic-calendar-revive/tree/master/LICENSE.md\">MIT license.</a>"
# Aux links for the upper right navigation
aux_links:
    "Atomic Calendar Revive on GitHub":
      - "//github.com/marksie1988/atomic-calendar-revive"
