---

name: Changelog CI

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: saadmk11/changelog-ci@v0.7.0
        with:
          config_file: changelog-ci-config.json
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

