name: Check Package Version

on:
  pull_request:
  workflow_dispatch:

jobs:
  checkVersion:
    name: Check version updated
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      # Use this GitHub Action
      - name: Check package version
        uses: dudo/tag_check@v1.0.0
        with:
          git_tag_prefix: v
